# derived from https://raw.githubusercontent.com/abarichello/godot-ci/master/.github/workflows/godot-ci.yml

name: "ci export"
on: push

env:
  EXPORT_NAME: combine_derby
  GODOT_VERSION: 4.2.1.stable.mono
  TEMPLATE_DIRECTORY: /root/.local/share/godot/templates/

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:mono-4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          git config --global --add safe.directory $(pwd)
          ./setBuildConstants.sh
          mkdir -v -p ~/.local/share/godot/export_templates
          mkdir -v -p ~/.config/godot
          mv ${TEMPLATE_DIRECTORY}/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
          mv /root/.config/godot/editor_settings-4.tres ~/.config/godot/editor_settings-4.tres
      - name: Windows Dependencies
        run: |
          dpkg --add-architecture i386 && apt-get update && apt-get install -y wine-stable && apt-get install -y wine32
          mkdir -v -p ~/.local/share/rcedit
          wget https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe -O ~/.local/share/rcedit/rcedit-x64.exe
          mkdir -p /github/home/.wine
          chown $USER:$USER -R ~
          echo 'export/windows/rcedit = "/github/home/.local/share/rcedit/rcedit-x64.exe"' >> ~/.config/godot/editor_settings-4.tres
      - name: Windows Build
        run: |
          wine ~/.local/share/rcedit/rcedit-x64.exe
          mkdir -v -p build/windows
          godot -v --headless --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: combine-derby-windows
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:mono-4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          git config --global --add safe.directory $(pwd)
          ./setBuildConstants.sh
          mkdir -v -p ~/.local/share/godot/export_templates
          mkdir -v -p ~/.config/godot
          mv ${TEMPLATE_DIRECTORY}/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
          mv /root/.config/godot/editor_settings-4.tres ~/.config/godot/editor_settings-4.tres
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot -v --headless --export-release "Linux/X11" build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: combine-derby-linux
          path: build/linux
