# derived from https://raw.githubusercontent.com/abarichello/godot-ci/master/.github/workflows/godot-ci.yml

name: "web deploy"
on:
  push:
    branches:
      - pages

env:
  GODOT_VERSION: 4.1.1.stable
  EXPORT_NAME: combine_derby

# permission for github pages push
permissions:
  contents: write

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          git config --global --add safe.directory $(pwd)
          ./setBuildConstants.sh
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --headless --export-release Web build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: combine-derby-web
          path: build/web
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y rsync curl
      # allows GH pages to run with the correct cross domain headers.
      - name: Install service worker script
        run: |
          curl https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.min.js > build/web/coi-serviceworker.min.js
      - name: Add service worker reference
        run: |
          sed -i 's#<head>#<head>\n\t\t<script src="coi-serviceworker.js"></script>#' build/web/combine-derby.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
